

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          # google id, secret? ??? scope ??? redirect uri? ?? ? ??? ?????.
          google:
            client-id: 857467487976-o8e8mq8v8hbca622k4fvdl7v4tbf2f94.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: C_sNgCno4J0ML90mNrRw
            client-secret: LcxJHvaizs
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

logging:
  level:
    org.springframework: info
    org.com: debug
    org:
      springframework:
        security: trace
