spring:
  batch:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/totomarket?useSSL=false&serverTimezone=UTC
    username: totomarketAdmin
    password: 1qaz@wsx3edc$rfv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true # JPQL 쿼리 로그 남기기

#    datasource:
#      url: jdbc:h2:tcp://localhost/~/test
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
#    jpa:
#      hibernate:
#        ddl-auto: create
#      properties:
#        hibernate:
#          format_sql: true
#          use_sql_comments: true # JPQL 쿼리 로그 남기기

logging:
  level:
    org.springframework: info
    org.com: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org:
      springframework:
        security: trace

com:
  main:
    upload:
      path: C:\\upload